env:
  browser: true
  es6: true
  node: true
  commonjs: true

extends: 'htmlacademy/es6'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parserOptions:
  ecmaVersion: 2018
  sourceType: module

rules: {}
